apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      NodePort: 30001
      protocol: TCP
      name: api      
  selector:
    name: pod-api2