apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-api
spec:
  replicas: 5
  template:
    metadata:
      labels:
       name: pod-api2
    spec:
      containers:
        - name: container-backend
          image: keyloguer/hackathon:v1.0
          ports:
          - containerPort: 80
            name: api
      restartPolicy: Always