version: '3'
services:
  mvc:
    image: exemplo6:0.4
    ports:
      - "80:80"
    depends_on: 
      - db
  db:
    build: ./sql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"